In [3]:
# read documentation form "numpy.org"
import numpy as np
import pandas as pd

# Creating a 1D array from a list
my_list = [1, 2, 3, 4, 5, 6]
numpy_array_1d = np.array(my_list)
print("1D Array:", numpy_array_1d)

1D Array: [1 2 3 4 5 6]


In [7]:
a = np.arange(12) #generate a list of numbers 0 to 11
print("new arr",a)
print("Dimension of a:", a.ndim)
print("Shapeof a:",a.shape)
print("data type of each element:",a.dtype)
print("-----------------------------------------")
b= a.reshape(3,4) #change the dim of an array
print("shape of b:",b.shape)
print(b)
print("Sum of all:",b.sum())
print("Row sum:",b.sum(axis=0)) #row sum
print(b.T) #transpose of an array
print("-----------------------------------------")
print(np.ravel(b)); #flatten an array

new arr [ 0  1  2  3  4  5  6  7  8  9 10 11]
Dimension of a: 1
Shapeof a: (12,)
data type of each element: int64
-----------------------------------------
shape of b: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sum of all: 66
Row sum: [12 15 18 21]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
-----------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
a= np.array([[1,2],[3,4]])
print (a)
print(a+3) #adds 3 to each element
print(a>3) #returns true if a number in the array is greater than 3(4>3) and false for others 

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]
[[False False]
 [False  True]]


In [33]:
m= np.array([[1,2],[3,4]])
n= np.array([[5,6],[7,8]])

print("m:\n",m)
print("n:\n",n)
print("-----------------------------------------")
print(m+n) #addition of two matrix
print("-----------------------------------------")
print(m*n) #multiply each element
print("-----------------------------------------")
print(m.dot(n)) #product of two array

m:
 [[1 2]
 [3 4]]
n:
 [[5 6]
 [7 8]]
-----------------------------------------
[[ 6  8]
 [10 12]]
-----------------------------------------
[[ 5 12]
 [21 32]]
-----------------------------------------
[[19 22]
 [43 50]]


In [35]:
print(np.sqrt(289))
np.float64(55)

17.0


np.float64(55.0)